# Generated by Django 5.2.1 on 2025-05-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
