# Generated by Django 5.2.1 on 2025-05-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='pointevent',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
