# Generated by Django 5.2.1 on 2025-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_profile_pic.jpeg', null=True, upload_to='images/'),
        ),
    ]
