# Generated by Django 5.2.1 on 2025-05-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_profile_pic.jpg', null=True, upload_to='images/'),
        ),
    ]
